# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

exclude: [vendor, "Gemfile", "Gemfile.lock"]

# Site settings
title: Stream of Soliloquy 
email: abhinavrajagopalan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    This is my personal web page where I like to mulldump on computing, science, philosophy and whatever else I feel like but mostly end up rubberducking myself. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://abvr.github.io" # the base hostname & protocol for your site

pages:
  markdown:
    extra: true
assets:
   sources:
       - assets/fonts
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - code
  - vendor
plugins:
  - jekyll-redirect-from
  
sass:
  sass_dir: _sass
  
social_links:

linkedin_username: abvr
github_username: abvr

disqus:
  shortname: abhinavrajagopalan-in

google_analytics: UA-168275953-1
# Build settings
markdown: kramdown
highlighter: rouge
